cntnzu – odepack
cntnzu Subroutine
30 statements
Source File
public subroutine cntnzu(N, Ia, Ja, Nzsut)
This routine counts the number of nonzero elements in the strict upper triangle of the matrix M + M(transpose), where the sparsity structure of M is given by pointer arrays IA and JA.
This is needed to compute the storage requirements for the sparse matrix reordering operation in ODRV.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
integer, intent(in) :: Ia(*)
integer, intent(in) :: Ja(*)
integer, intent(out) :: Nzsut
Called by
Contents
None
Call graph
dprepi calls cntnzu
dprep calls wrapup600
diprepi calls dprepi
diprep calls dprep
dlsodis calls diprepi
dlsodes calls diprep