dcopy – odepack
dcopy Subroutine
47 statements
Source File
subroutine dcopy(N, Dx, Incx, Dy, Incy)
NAME
dcopy(3f) - [M_odepack::matrix] copy a vector
SYNOPSIS
    subroutine dcopy(N,Dx,Incx,Dy,Incy)
    integer,intent(in)        :: N
    real(kind=dp),intent(in)  :: Dx(*)
    integer,intent(in)        :: Incx
    real(kind=dp),intent(out) :: Dy(*)
    integer,intent(in)        :: Incy
DESCRIPTION
Copy double precision DX to double precision DY. For I = 0 to N-1, copy DX(LX+IINCX) to DY(LY+IINCY), where LX = 1 if INCX .GE. 0, else LX = 1+(1-N)*INCX, and LY is defined in a similar way using INCY.
INPUT OPTIONS
N
number of elements in input vector(s)
DX
double precision vector with N elements
INCX
storage spacing between elements of DX
DY
double precision vector with N elements
INCY
storage spacing between elements of DY
RETURNS
DY
copy of vector DX (unchanged if N .LE. 0)
REFERENCES
B L A S Subprogram
C. L. Lawson, R. J. Hanson, D. R. Kincaid and F. T.
Krogh, Basic linear algebra subprograms for Fortran
usage, Algorithm No. 539, Transactions on Mathematical
Software 5, 3 (September 1979), pp. 308-323.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=dp), intent(in) :: Dx(*)
integer, intent(in) :: Incx
real(kind=dp), intent(out) :: Dy(*)
integer, intent(in) :: Incy
Called by
Contents
Variables
i ix iy m mp1 ns
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: ix
integer, public :: iy
integer, public :: m
integer, public :: mp1
integer, public :: ns
Call graph
dpcg calls dcopy, datp
dsolpk calls dcopy, dpcg, dpcgs, dspigmr, dspiom, dusol
dpcgs calls dcopy, datp
dlsodkr calls dcopy, dlhin, drchek, dstoka
dlsodar calls dcopy, drchek
dlhin calls dcopy
datp calls dcopy
dspigmr calls dcopy
dspiom calls dcopy
droots calls dcopy
drchek calls dcopy, droots
dusol calls dcopy
dstodpk calls dsolpk
dstoka calls dsolpk
dlsodpk calls dstodpk