dewset – odepack
dewset Subroutine
27 statements
Source File
public subroutine dewset(N, Itol, Rtol, Atol, Ycur, Ewt)
NAME
dewset(3f) - [M_odepack] Set error weight vector.
SYNOPSIS
    subroutine dewset(N,Itol,Rtol,Atol,Ycur,Ewt)
    integer,intent(in)        :: N
    integer,intent(in)        :: Itol
    real(kind=dp),intent(in)  :: Rtol(*)
    real(kind=dp),intent(in)  :: Atol(*)
    real(kind=dp),intent(in)  :: Ycur(N)
    real(kind=dp),intent(out) :: Ewt(N)
DESCRIPTION
This subroutine sets the error weight vector EWT according to
   EWT(i) = RTOL(i)*ABS(YCUR(i)) + ATOL(i),  i = 1,...,N,
with the subscript on RTOL and/or ATOL possibly replaced by 1 above, depending on the value of ITOL.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
integer, intent(in) :: Itol
real(kind=dp), intent(in) :: Rtol(*)
real(kind=dp), intent(in) :: Atol(*)
real(kind=dp), intent(in) :: Ycur(N)
real(kind=dp), intent(out) :: Ewt(N)
Called by
Call graph
dlsoda calls dewset
dlsodar calls dewset
dlsodes calls dewset
dlsode calls dewset
dlsodis calls dewset
dlsodi calls dewset
dlsodkr calls dewset
dlsodpk calls dewset
dlsoibt calls dewset