dgesl – odepack
dgesl Subroutine
46 statements
Source File
subroutine dgesl(A, Lda, N, Ipvt, B, Job)
NAME
dgesl(3f) - [M_odepack::matrix] Solve the real system AX=B or TRANS(A)X=B using the factors computed by DGECO or DGEFA.
SYNOPSIS
subroutine dgesl(A,Lda,N,Ipvt,B,Job)
real(kind=dp)               :: A(Lda,*)
integer,intent(in)          :: Lda
integer,intent(in)          :: N
integer,intent(in)          :: Ipvt(*)
real(kind=dp),intent(inout) :: B(*)
integer,intent(in)          :: Job
DESCRIPTION
DGESL solves the double precision system
    A * X = B  or  TRANS(A) * X = B
using the factors computed by DGECO or DGEFA.
Error Condition
    A division by zero will occur if the input factor contains a
    zero on the diagonal.  Technically this indicates singularity
    but it is often caused by improper arguments or improper
    setting of LDA .  It will not occur if the subroutines are
    called correctly and if DGECO has set RCOND .GT. 0.0
    or DGEFA has set INFO .EQ. 0 .
To compute INVERSE(A) * C where C is a matrix with P columns
       CALL DGECO(A,LDA,N,IPVT,RCOND,Z)
       IF (RCOND is too small) GO TO ...
       DO J = 1, P
          CALL DGESL(A,LDA,N,IPVT,C(1,J),0)
       ENDDO
ON ENTRY
A
the output from DGECO or DGEFA.
LDA
the leading dimension of the array A .
N
the order of the matrix A .
IPVT
the pivot vector from DGECO or DGEFA.
B
the right hand side vector.
JOB
: = 0 to solve AX = B , = nonzero to solve TRANS(A)X = B where TRANS(A) is the transpose.
ON RETURN
B
the solution vector X .
REFERENCES
J. J. Dongarra, J. R. Bunch, C. B. Moler, and G. W. Stewart, LINPACK Users’ Guide, SIAM, 1979.
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: A(Lda,*)
integer, intent(in) :: Lda
integer, intent(in) :: N
integer, intent(in) :: Ipvt(*)
real(kind=dp), intent(inout) :: B(*)
integer, intent(in) :: Job
Calls
Called by
Contents
Variables
k kb l nm1 t
Variables
Type Visibility Attributes Name Initial
integer, public :: k
integer, public :: kb
integer, public :: l
integer, public :: nm1
real(kind=dp), public :: t
Call graph
dgesl calls daxpy, ddot
dainvg calls dgesl
dsolsy calls dgesl
ddecbt calls dgesl
dsolbt calls dgesl
dpjibt calls ddecbt
dslsbt calls dsolbt
daigbt calls ddecbt, dsolbt
dlsodi calls dainvg
dlsoibt calls daigbt