dhels – odepack
dhels Subroutine
25 statements
Source File
subroutine dhels(A, Lda, N, Q, B)
This is part of the LINPACK routine DGESL with changes due to the fact that A is an upper Hessenberg matrix.
DHELS solves the least squares problem
       min (b-A*x, b-A*x)
 using the factors computed by DHEQR.
On entry
    A       DOUBLE PRECISION(LDA, N)
            the output from DHEQR which contains the upper
            triangular factor R in the QR decomposition of A.
    LDA     INTEGER
            the leading dimension of the array  A .
    N       INTEGER
            A is originally an (N+1) by N matrix.
    Q       DOUBLE PRECISION(2*N)
            The coefficients of the N givens rotations
            used in the QR factorization of A.
    B       DOUBLE PRECISION(N+1)
            the right hand side vector.
On return
    B       the solution vector  x .
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: A(Lda,*)
integer, intent(in) :: Lda
integer, intent(in) :: N
real(kind=dp), intent(in) :: Q(*)
real(kind=dp), intent(inout) :: B(*)
Calls
Called by
Contents
Variables
c iq k kb kp1 s t t1 t2
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: c
integer, public :: iq
integer, public :: k
integer, public :: kb
integer, public :: kp1
real(kind=dp), public :: s
real(kind=dp), public :: t
real(kind=dp), public :: t1
real(kind=dp), public :: t2
Call graph
dhels calls daxpy
dspigmr calls approximate
dsolpk calls dspigmr
dstodpk calls dsolpk
dstoka calls dsolpk
dlsodpk calls dstodpk
dlsodkr calls dstoka