dintdy – odepack
dintdy Subroutine
62 statements
Source File
public subroutine dintdy(T, K, Yh, Nyh, Dky, Iflag)
DESCRIPTION
DINTDY computes interpolated values of the K-th derivative of the dependent variable vector y, and stores it in DKY. This routine is called within the package with K = 0 and T = TOUT, but may also be called by the user for any K up to the current order. (See detailed instructions in the usage documentation.)
The computed values in DKY are gotten by interpolation using the Nordsieck history array YH. This array corresponds uniquely to a vector-valued polynomial of degree NQCUR or less, and DKY is set to the K-th derivative of this polynomial at T. The formula for DKY is:
               q
   DKY(i)  =  sum  c(j,K) * (T - tn)**(j-K) * h**(-j) * YH(i,j+1)
              j=K
where c(j,K) = j(j-1)…*(j-K+1), q = NQCUR, tn = TCUR, h = HCUR.
The quantities nq = NQCUR, l = nq+1, N = NEQ, tn, and h are communicated by COMMON. The above sum is done in reverse order. IFLAG is returned negative if either K or T is out of bounds.
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: T
integer :: K
real(kind=dp), intent(in) :: Yh(Nyh,*)
integer, intent(in) :: Nyh
real(kind=dp), intent(inout) :: Dky(*)
integer, intent(out) :: Iflag
Calls
Called by
Contents
None
Call graph
dintdy calls xerrwd
drchek calls dintdy
dlsodkr calls dintdy, drchek
dlsodi calls dintdy
dlsode calls dintdy
dlsoda calls dintdy
dlsodes calls dintdy
dlsodar calls dintdy, drchek
dlsodis calls dintdy
dlsodpk calls dintdy
dlsoibt calls dintdy