diprep – odepack
diprep Subroutine
35 statements
Source File
public subroutine diprep(Neq, Y, Rwork, Ia, Ja, Ipflag, f, jac)
This routine serves as an interface between the driver and Subroutine DPREP. It is called only if MITER is 1 or 2. Tasks performed here are:
call DPREP,
reset the required WM segment length LENWK,
move YH back to its final location (following WM in RWORK),
reset pointers for YH, SAVF, EWT, and ACOR, and
move EWT to its new position if ISTATE = 1.
IPFLAG is an output error indication flag. IPFLAG = 0 if there was no trouble, and IPFLAG is the value of the DPREP error flag IPPER if there was trouble in Subroutine DPREP.
Arguments
Type Intent Optional Attributes Name
integer :: Neq(*)
real(kind=dp) :: Y(*)
real(kind=dp), intent(inout) :: Rwork(*)
integer :: Ia(*)
integer :: Ja(*)
integer, intent(inout) :: Ipflag
real :: f
integer :: jac
Calls
Called by
Contents
None
Call graph
diprep calls dprep
dprep calls wrapup500, wrapup700, adjlr, wrapup600, wrapup400, odrv, jgroup, cdrv
dlsodes calls diprep