dmnorm – odepack
dmnorm Function
13 statements
Source File
public pure function dmnorm(n, v, w)
This function routine computes the weighted max-norm of the vector of length N contained in the array V, with weights contained in the array w of length N: DMNORM = MAX(i=1,…,N) ABS(V(i))*W(i)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=dp), intent(in) :: v(n)
real(kind=dp), intent(in) :: w(n)
Return Value real(kind=dp)
Called by
Contents
None
Call graph
dlsodar calls dmnorm, dstoda
dprja calls dmnorm
dlsoda calls dmnorm, dstoda
dstoda calls dmnorm