dnrm2 – odepack
dnrm2 Function
65 statements
Source File
pure function dnrm2(n, dx, incx)
NAME
dnrm2(3f) - [M_odepack::matrix] Compute the Euclidean length (L2 norm) of a vector.
DESCRIPTION
Euclidean norm of the N-vector stored in DX with storage increment INCX.
   If N .LE. 0, return with result = 0.
   If N .GE. 1, then INCX must be .GE. 1
Four phase method using two built-in constants that are hopefully applicable to all machines.
     CUTLO = maximum of  SQRT(U/EPS)  over all known machines.
     CUTHI = minimum of  SQRT(V)      over all known machines.
where
     EPS = smallest no. such that EPS + 1. .GT. 1.
     U   = smallest positive no.   (underflow limit)
     V   = largest  no.            (overflow  limit)
Brief outline of algorithm.
   Phase 1 scans zero components.
   move to phase 2 when a component is nonzero and .LE. CUTLO
   move to phase 3 when a component is .GT. CUTLO
   move to phase 4 when a component is .GE. CUTHI/M
   where M = N for X() real and M = 2*N for complex.
INPUT
N
number of elements in input vector(s)
DX
double precision vector with N elements
INCX
storage spacing between elements of DX
OUTPUT
DNRM2
double precision result (zero if N .LE. 0)
Values for CUTLO and CUTHI.
From the environmental parameters listed in the IMSL converter document the limiting values are as follows:
      CUTLO, S.P.   U/EPS = 2**(-102) for  Honeywell.  Close seconds are
                    Univac and DEC at 2**(-103)
                    Thus CUTLO = 2**(-51) = 4.44089E-16
      CUTHI, S.P.   V = 2**127 for Univac, Honeywell, and DEC.
                    Thus CUTHI = 2**(63.5) = 1.30438E19
      CUTLO, D.P.   U/EPS = 2**(-67) for Honeywell and DEC.
                    Thus CUTLO = 2**(-33.5) = 8.23181D-11
      CUTHI, D.P.   same as S.P.  CUTHI = 1.30438D19
      DATA CUTLO, CUTHI /8.232D-11,  1.304D19/
      DATA CUTLO, CUTHI /4.441E-16,  1.304E19/
REFERENCES
B L A S Subprogram
C. L. Lawson, R. J. Hanson, D. R. Kincaid and F. T. Krogh, Basic linear algebra subprograms for Fortran usage, Algorithm No. 539, Transactions on Mathematical Software 5, 3 (September 1979), pp. 308-323.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=dp), intent(in) :: dx(*)
integer, intent(in) :: incx
Return Value real(kind=dp)
Called by
Contents
Variables
cuthi cutlo hitest i j next nn one sum xmax zero
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, parameter :: cuthi = 1.304d19
real(kind=dp), public, parameter :: cutlo = 8.232d-11
real(kind=dp), public :: hitest
integer, public :: i
integer, public :: j
integer, public :: next
integer, public :: nn
real(kind=dp), public, parameter :: one = 1.0d0
real(kind=dp), public :: sum
real(kind=dp), public :: xmax
real(kind=dp), public, parameter :: zero = 0.0d0
Call graph
dspigmr calls dnrm2, datv, dorthog
datv calls dnrm2
dspiom calls dnrm2, datv, dorthog
dorthog calls dnrm2
dsolpk calls dspigmr, dspiom
dstodpk calls dsolpk
dstoka calls dsolpk
dlsodkr calls dstoka
dlsodpk calls dstodpk