dstode – odepack
dstode Subroutine
358 statements
Source File
subroutine dstode(Neq, Y, Yh, Nyh, Yh1, Ewt, Savf, Acor, Wm, Iwm, f, jac, pjac, slvs)
Uses
M_odepack
NAME
dstode(3f) - [M_odepack] Performs one step of an ODEPACK integration.
DESCRIPTION
DSTODE performs one step of the integration of an initial value problem for a system of ordinary differential equations.
Note: DSTODE is independent of the value of the iteration method indicator MITER, when this is .ne. 0, and hence is independent of the type of chord method used, or the Jacobian structure.
Communication with DSTODE is done with the following variables:
NEQ
integer array containing problem size in NEQ(1), and passed as the NEQ argument in all calls to F and JAC.
Y
an array of length .ge. N used as the Y argument in all calls to F and JAC.
YH
an NYH by LMAX array containing the dependent variables and their approximate scaled derivatives, where LMAX = MAXORD + 1. YH(i,j+1) contains the approximate j-th derivative of y(i), scaled by h**j/factorial(j) (j = 0,1,…,NQ). on entry for the first step, the first two columns of YH must be set from the initial values.
NYH
a constant integer .ge. N, the first dimension of YH.
YH1
a one-dimensional array occupying the same space as YH.
EWT
an array of length N containing multiplicative weights for local error measurements. Local errors in Y(i) are compared to 1.0/EWT(i) in various error tests.
SAVF
an array of working storage, of length N. Also used for input of YH(*,MAXORD+2) when JSTART = -1 and MAXORD .lt. the current order NQ.
ACOR
a work array of length N, used for the accumulated corrections. On a successful return, ACOR(i) contains the estimated one-step local error in Y(i).
WM,IWM
real and integer work arrays associated with matrix operations in chord iteration (MITER .ne. 0).
PJAC
name of routine to evaluate and preprocess Jacobian matrix and P = I - hel0JAC, if a chord method is being used.
SLVS
name of routine to solve linear system in chord iteration.
CCMAX
maximum relative change in h*el0 before PJAC is called.
H
the step size to be attempted on the next step. H is altered by the error control algorithm during the problem. H can be either positive or negative, but its sign must remain constant throughout the problem.
HMIN
the minimum absolute value of the step size h to be used.
HMXI
inverse of the maximum absolute value of h to be used. HMXI = 0.0 is allowed and corresponds to an infinite hmax. HMIN and HMXI may be changed at any time, but will not take effect until the next change of h is considered.
TN
the independent variable. TN is updated on each step taken.
JSTART
an integer used for input only, with the following values and meanings: 0 perform the first step. .gt.0 take a new step continuing from the last. -1 take the next step with a new value of H, MAXORD, N, METH, MITER, and/or matrix parameters. -2 take the next step with a new value of H, but with other inputs unchanged. On return, JSTART is set to 1 to facilitate continuation.
KFLAG
a completion code with the following meanings: 0 the step was succesful. -1 the requested error could not be achieved. -2 corrector convergence could not be achieved. -3 fatal error in PJAC or SLVS.
A return with KFLAG = -1 or -2 means either abs(H) = HMIN or 10 consecutive failures occurred. On a return with KFLAG negative, the values of TN and the YH array are as of the beginning of the last step, and H is the last step size attempted.
MAXORD
the maximum order of integration method to be allowed.
MAXCOR
the maximum number of corrector iterations allowed.
MSBP
maximum number of steps between PJAC calls (MITER .gt. 0).
MXNCF
maximum number of convergence failures allowed.
METH/MITER
the method flags. See description in driver.
N
the number of first-order differential equations.
The values of CCMAX, H, HMIN, HMXI, TN, JSTART, KFLAG, MAXORD, MAXCOR, MSBP, MXNCF, METH, MITER, and N are communicated via COMMON.
Arguments
Type Intent Optional Attributes Name
integer :: Neq(*)
real(kind=dp), intent(inout) :: Y(*)
real(kind=dp), intent(inout) :: Yh(Nyh,*)
integer :: Nyh
real(kind=dp), intent(inout) :: Yh1(*)
real(kind=dp) :: Ewt(*)
real(kind=dp), intent(inout) :: Savf(*)
real(kind=dp), intent(inout) :: Acor(*)
real(kind=dp) :: Wm(*)
integer :: Iwm(*)
real :: f
integer :: jac
real :: pjac
real :: slvs
Calls
Called by
Contents
Variables
dcon ddn del delp dp dsm dup exdn exsm exup i i1 iredo iret j jb m ncf newq r rh rhdn rhsm rhup told
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: dcon
real(kind=dp), public :: ddn
real(kind=dp), public :: del
real(kind=dp), public :: delp
integer, public, parameter :: dp = kind(0.0d0)
real(kind=dp), public :: dsm
real(kind=dp), public :: dup
real(kind=dp), public :: exdn
real(kind=dp), public :: exsm
real(kind=dp), public :: exup
integer, public :: i
integer, public :: i1
integer, public :: iredo
integer, public :: iret
integer, public :: j
integer, public :: jb
integer, public :: m
integer, public :: ncf
integer, public :: newq
real(kind=dp), public :: r
real(kind=dp), public :: rh
real(kind=dp), public :: rhdn
real(kind=dp), public :: rhsm
real(kind=dp), public :: rhup
real(kind=dp), public :: told
Call graph
dstode calls dcfode, dvnorm
dlsode calls dstode
dlsodes calls dstode