dstodi – odepack
dstodi Subroutine
361 statements
Source File
subroutine dstodi(Neq, Y, Yh, Nyh, Yh1, Ewt, Savf, Savr, Acor, Wm, Iwm, res, adda, jac, pjac, slvs)
Uses
M_odepack
DSTODI performs one step of the integration of an initial value problem for a system of Ordinary Differential Equations.
Note: DSTODI is independent of the value of the iteration method indicator MITER, and hence is independent of the type of chord method used, or the Jacobian structure.
Communication with DSTODI is done with the following variables:
NEQ
integer array containing problem size in NEQ(1), and passed as the NEQ argument in all calls to RES, ADDA, and JAC.
Y
an array of length .ge. N used as the Y argument in all calls to RES, JAC, and ADDA.
NEQ
integer array containing problem size in NEQ(1), and passed as the NEQ argument in all calls tO RES, G, ADDA, and JAC.
YH
an NYH by LMAX array containing the dependent variables and their approximate scaled derivatives, where
LMAX
MAXORD + 1. YH(i,j+1) contains the approximate j-th derivative of y(i), scaled by H**j/factorial(j) (j = 0,1,…,NQ). On entry for the first step, the first two columns of YH must be set from the initial values.
NYH
a constant integer .ge. N, the first dimension of YH.
YH1
a one-dimensional array occupying the same space as YH.
EWT
an array of length N containing multiplicative weights for local error measurements. Local errors in y(i) are compared to 1.0/EWT(i) in various error tests.
SAVF
an array of working storage, of length N. also used for input of YH(*,MAXORD+2) when JSTART = -1 and MAXORD is less than the current order NQ. Same as YDOTI in the driver.
SAVR
an array of working storage, of length N.
ACOR
a work array of length N used for the accumulated corrections. On a succesful return, ACOR(i) contains the estimated one-step local error in y(i).
WM,IWM
real and integer work arrays associated with matrix operations in chord iteration.
PJAC
name of routine to evaluate and preprocess Jacobian matrix.
SLVS
name of routine to solve linear system in chord iteration.
CCMAX
maximum relative change in H*EL0 before PJAC is called.
H
the step size to be attempted on the next step. H is altered by the error control algorithm during the problem. H can be either positive or negative, but its sign must remain constant throughout the problem.
HMIN
the minimum absolute value of the step size H to be used.
HMXI
inverse of the maximum absolute value of H to be used. HMXI = 0.0 is allowed and corresponds to an infinite HMAX. HMIN and HMXI may be changed at any time, but will not take effect until the next change of H is considered.
TN
the independent variable. TN is updated on each step taken.
JSTART
an integer used for input only, with the following values and meanings:
      0  perform the first step.
  .gt.0  take a new step continuing from the last.
     -1  take the next step with a new value of H, MAXORD,
         N, METH, MITER, and/or matrix parameters.
     -2  take the next step with a new value of H,
         but with other inputs unchanged.
         On return, JSTART is set to 1 to facilitate continuation.
KFLAG
a completion code with the following meanings:
      0  the step was succesful.
     -1  the requested error could not be achieved.
     -2  corrector convergence could not be achieved.
     -3  RES ordered immediate return.
     -4  error condition from RES could not be avoided.
     -5  fatal error in PJAC or SLVS.
A return with KFLAG = -1, -2, or -4 means either
ABS(H)
HMIN or 10 consecutive failures occurred.
On a return with KFLAG negative, the values of TN and the YH array are as of the beginning of the last step, and H is the last step size attempted.
MAXORD
the maximum order of integration method to be allowed.
MAXCOR
the maximum number of corrector iterations allowed.
MSBP
maximum number of steps between PJAC calls.
MXNCF
maximum number of convergence failures allowed. METH/MITER = the method flags. See description in driver.
N
the number of first-order differential equations.
Arguments
Type Intent Optional Attributes Name
integer, dimension(*) :: Neq
real(kind=dp), dimension(*) :: Y
real(kind=dp), intent(inout), dimension(Nyh,*) :: Yh
integer :: Nyh
real(kind=dp), intent(inout), dimension(*) :: Yh1
real(kind=dp), dimension(*) :: Ewt
real(kind=dp), dimension(*) :: Savf
real(kind=dp), dimension(*) :: Savr
real(kind=dp), intent(inout), dimension(*) :: Acor
real(kind=dp), dimension(*) :: Wm
integer, dimension(*) :: Iwm
real :: res
real :: adda
integer :: jac
real :: pjac
real :: slvs
Calls
Called by
Contents
Variables
dcon ddn del delp dp dsm dup el1h eljh exdn exsm exup i i1 iredo ires iret j jb kgo m ncf newq r rh rhdn rhsm rhup told
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: dcon
real(kind=dp), public :: ddn
real(kind=dp), public :: del
real(kind=dp), public :: delp
integer, public, parameter :: dp = kind(0.0d0)
real(kind=dp), public :: dsm
real(kind=dp), public :: dup
real(kind=dp), public :: el1h
real(kind=dp), public :: eljh
real(kind=dp), public :: exdn
real(kind=dp), public :: exsm
real(kind=dp), public :: exup
integer, public :: i
integer, public :: i1
integer, public :: iredo
integer, public :: ires
integer, public :: iret
integer, public :: j
integer, public :: jb
integer, public :: kgo
integer, public :: m
integer, public :: ncf
integer, public :: newq
real(kind=dp), public :: r
real(kind=dp), public :: rh
real(kind=dp), public :: rhdn
real(kind=dp), public :: rhsm
real(kind=dp), public :: rhup
real(kind=dp), public :: told
Call graph
dstodi calls dcfode, dvnorm
dlsoibt calls dstodi
dlsodi calls dstodi
dlsodis calls dstodi