dumach – odepack
dumach Function
19 statements
Source File
function dumach()
NAME
dumach(3f) - [M_odepack] Compute the unit roundoff of the machine.
SYNOPSIS
    a = dumach()
    double precision :: dumach
    double precision :: a
DESCRIPTION
The unit roundoff is defined as the smallest positive machine number u such that 1.0 + u .ne. 1.0. This is computed by DUMACH in a machine-independent manner.
RETURNS
A
the unit roundoff of the machine.
Arguments
None
Return Value real(kind=dp)
Calls
Called by
Contents
Variables
comp u
Subroutines
dumsum
Source Code
dumach
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: comp
real(kind=dp), public :: u
Subroutines
subroutine dumsum(a, b, c)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: a
real(kind=dp), intent(in) :: b
real(kind=dp), intent(out) :: c
Source Code
function dumach()
real(kind=dp) :: dumach
real(kind=dp) :: u, comp
    u = 1.0d0
    do
        u = u * 0.5d0
        call dumsum( 1.0d0, u, comp )
        if ( comp == 1.0d0 ) then
           dumach = u * 2.0d0
           exit
        endif
    enddo
contains
subroutine dumsum(a,b,c)
!  Routine to force normal storing of A + B, for DUMACH.
real(kind=dp),intent(in)  :: a, b
real(kind=dp),intent(out) :: c
    c = a + b
end subroutine dumsum
end function dumach
Call graph
dumach calls dumsum
dlsoibt calls dumach
dlsodi calls dumach
dlsodis calls dumach
dlsodpk calls dumach
dlsodar calls dumach
dlsodes calls dumach
dlsode calls dumach
dlsodkr calls dumach
dlsoda calls dumach