dumach – odepack
dumach Function
19 statements
Source File
public function dumach()
NAME
dumach(3f) - [M_odepack] Compute the unit roundoff of the machine.
SYNOPSIS
    a = dumach()
    double precision :: dumach
    double precision :: a
DESCRIPTION
The unit roundoff is defined as the smallest positive machine number u such that 1.0 + u .ne. 1.0. This is computed by DUMACH in a machine-independent manner.
RETURNS
A
the unit roundoff of the machine.
Arguments
None
Return Value real(kind=dp)
Called by
Contents
None
Call graph
dlsodpk calls dumach
dlsodis calls dumach
dlsoda calls dumach
dlsodkr calls dumach
dlsodar calls dumach
dlsodes calls dumach
dlsoibt calls dumach
dlsode calls dumach
dlsodi calls dumach