dvnorm – odepack
dvnorm Function
13 statements
Source File
public pure function dvnorm(n, v, w)
NAME
dvnorm(3f) - [M_odepack] Weighted root-mean-square vector norm.
DESCRIPTION
This function routine computes the weighted root-mean-square norm of the vector of length N contained in the array V, with weights contained in the array W of length N:
    DVNORM = SQRT( (1/N) * SUM( V(i)*W(i) )**2 )
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=dp), intent(in) :: v(n)
real(kind=dp), intent(in) :: w(n)
Return Value real(kind=dp)
Called by
Contents
None
Call graph
dstodi calls dvnorm
dlsodes calls dvnorm, dstode
dstode calls dvnorm
dlsode calls dvnorm, dstode
dlsodis calls dvnorm, dstodi
dstoka calls dvnorm
dlsodpk calls dvnorm, dstodpk
dstodpk calls dvnorm
dprepj calls dvnorm
dprjs calls dvnorm
dlhin calls dvnorm
dlsodi calls dvnorm, dstodi
dlsodkr calls dvnorm, dstoka, dlhin
dlsoibt calls dvnorm, dstodi