jgroup – odepack
jgroup Subroutine
52 statements
Source File
public subroutine jgroup(N, Ia, Ja, Maxg, Ngrp, Igp, Jgp, Incl, Jdone, Ier)
This subroutine constructs groupings of the column indices of the Jacobian matrix, used in the numerical evaluation of the Jacobian by finite differences.
Input:
N
the order of the matrix.
IA,JA
sparse structure descriptors of the matrix by rows.
MAXG
length of available storage in the IGP array.
Output:
NGRP
number of groups.
JGP
array of length N containing the column indices by groups.
IGP
pointer array of length NGRP + 1 to the locations in JGP of the beginning of each group.
IER
error indicator. IER = 0 if no error occurred, or 1 if MAXG was insufficient.
INCL and JDONE are working arrays of length N.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
integer, intent(in), dimension(*) :: Ia
integer, intent(in), dimension(*) :: Ja
integer, intent(in) :: Maxg
integer, intent(out) :: Ngrp
integer, intent(inout), dimension(*) :: Igp
integer, intent(out), dimension(*) :: Jgp
integer, intent(inout), dimension(*) :: Incl
integer, intent(inout), dimension(*) :: Jdone
integer, intent(out) :: Ier
Called by
Contents
None
Call graph
dprepi calls jgroup
dprep calls jgroup
diprep calls dprep
diprepi calls dprepi
dlsodis calls diprepi
dlsodes calls diprep